dymola_ci_test_dir = 'dymola-ci-tests'
dymola_python_test_dir = 'Dymola_python_tests'

[whitelist]
wh_ci_dir = "dymola_ci_test_dir/ci_whitelist"
wh_model_file = 'wh_ci_dir/ci_check_whitelist.txt'
wh_simulate_file = 'wh_ci_dir/ci_simulate_whitelist.txt'
wh_html_file = 'wh_ci_dir/ci_html_whitelist.txt'
wh_ref_file = 'wh_ci_dir/ci_reference_check_whitelist.txt'

[config_ci]
config_ci_dir = 'dymola_ci_test_dir/Configfiles'
config_ci_exit_file = 'config_ci_dir/exit.sh'
config_ci_new_ref_file = 'config_ci_dir/ci_new_ref_file.txt'
config_ci_new_create_ref_file = 'config_ci_dir/ci_new_created_reference.txt'
config_ci_changed_file = 'config_ci_dir/ci_changed_model_list.txt'
config_ci_ref_file = 'config_ci_dir/ci_reference_list.txt'
config_ci_eof_file = 'config_ci_dir/EOF.sh'

[template_plot]
chart_dir = 'dymola_ci_test_dir/charts'
temp_chart_dir = 'dymola_python_test_dir/templates/google_templates'
temp_chart_file = 'temp_chart_dir/google_chart.txt'
temp_index_file = 'temp_chart_dir/index.txt'
temp_layout_file = 'temp_chart_dir/layout_index.txt'

[interact_ci_list]
ci_interact_dir = 'dymola_ci_test_dir/interact_CI'
ci_interact_show_ref_file = 'ci_interact_dir/show_ref.txt'
ci_interact_update_ref_file = 'ci_interact_dir/update_ref.txt'

[folder]
artifacts_dir = 'dymola_ci_test_dir/templates/artifacts'
library_ref_results_dir = 'Resources/ReferenceResults/Dymola'
library_resource_dir = 'Resources/Scripts/Dymola'
[Dymola_Python_Tests]
dymola_python_test_url = 'https://$CI_TEST_Name:$CI_TEST_TOKEN@git.rwth-aachen.de/EBC/EBC_all/gitlab_ci/Dymola_python_tests.git'