[api_github.Parser]
github_repository = "RWTH-EBC/AixLib"
working_branch = "${TARGET_BRANCH}"
base_branch = "main"
github_token = "${GITHUB_API_TOKEN}"
gitlab_page = "https://ebc.pages.rwth-aachen.de/EBC_all/github_ci/AixLib"
prepare_plot_flag = false
show_plot_flag = false
post_pr_comment_flag = false
create_pr_flag = false
correct_html_flag = false
ibpsa_merge_flag = false
merge_request = false

[api_slack.Parser]
github_token = "${GITHUB_API_TOKEN}"
base_branch = "development"
slack_token = "${secrets.SLACK_BOT_TOKEN}"
github_repository = "RWTH-EBC/AixLib"

[structure_check.Parser]
config_dir = false
create_path = false

[google_charts.Parser]
packages = [ "Airflow", "BoundaryConditions", "Controls", "Electrical", "Fluid", "Media", "Systems", "ThermalZones", "Utilities",]
library = [ "AixLib",]
line_html_flag = true
error_flag = true
funnel_comp_flag = true
create_layout_flag = true
line_matplot_flag = false
new_ref_flag = false
show_ref_flag = false
update_ref_flag = false
show_package_flag = false
ref_txt_flag = false

[lock_model.Parser]
library = [ "AixLib",]
lock_library = "IBPSA"

[library_merge.Parser]
library_dir = "AixLib\\Resources\\Scripts"
merge_library_dir = "modelica-ibpsa\\IBPSA\\Resources\\Scripts\\Dymola\\ConvertIBPSA_*"
mos_path = "Convertmos"
library = [ "AixLib",]
merge_library = "IBPSA"

[html_tidy_errors.Parser]
packages = [ "Airflow", "BoundaryConditions", "Controls", "Electrical", "Fluid", "Media", "Systems", "ThermalZones", "Utilities",]
library = [ "AixLib",]
wh_library = [ "IBPSA",]
git_url = "https://github.com/ibpsa/modelica-ibpsa.git"
repo_dir = "modelica-ibpsa"
root_wh_library = "None"
correct_overwrite_flag = false
correct_backup_flag = false
log_flag = false
whitelist_flag = false
correct_view_flag = false
filter_whitelist_flag = false

[StyleChecking.Parser]
packages = [ "Airflow", "BoundaryConditions", "Controls", "Electrical", "Fluid", "Media", "Systems", "ThermalZones", "Utilities",]
root_library = [ "AixLib/package.mo",]
library = [ "AixLib",]
dymola_version = "2022"
changed_flag = true

[OM_Check.Parser]
library = [ "AixLib",]
packages = [ "Airflow", "BoundaryConditions", "Controls", "Electrical", "Fluid", "Media", "Systems", "ThermalZones", "Utilities",]
root_library = [ "AixLib/package.mo",]
wh_library = [ "IBPSA",]
changed_flag = true
filter_wh_flag = true
extended_ex_flag = true
load_setting_flag = false
om_options = [ "OM_CHECK",]

[reference_check.Parser]
library = [ "AixLib",]
packages = [ "Airflow", "BoundaryConditions", "Controls", "Electrical", "Fluid", "Media", "Systems", "ThermalZones", "Utilities",]
root_library = [ "AixLib/package.mo",]
path = "."
show_gui = false
number_of_processors = 4
tool = "dymola"
dymola_version = "2022"
batch = true
coverage_only = false
create_ref = false
ref_list = false
update_ref = false
changed_flag = true
validate_html_only = false
validate_experiment_setup = false
report = false

[validatetest.Parser]
library = [ "AixLib",]
packages = [ "Airflow", "BoundaryConditions", "Controls", "Electrical", "Fluid", "Media", "Systems", "ThermalZones", "Utilities",]
root_library = [ "AixLib/package.mo",]
wh_library = [ "IBPSA",]
root_wh_library = "None"
dymola_version = "2022"
changed_flag = true
filter_wh_flag = true
extended_ex_flag = true
create_wh_flag = false
load_setting_flag = false
dym_options = [ "DYM_CHECK",]
repo_dir = "modelica-ibpsa"
git_url = "https://github.com/ibpsa/modelica-ibpsa.git"
