[api_github.Parser]
correct_branch = "${Newbranch}"
github_repository = "df"
working_branch = "${TARGET_BRANCH}"
base_branch = "main"
github_token = "${GITHUB_API_TOKEN}"
prepare_plot = false
show_plot = false
post_pr_comment = false
create_pr = false
correct_html = false
ibpsa_merge = false
merge_request = false
gitlab_page = "fdg"

[api_slack.Parser]
github_token = "${GITHUB_API_TOKEN}"
base_branch = "development"
slack_token = "${secrets.SLACK_BOT_TOKEN}"
github_repository = "df"

[structure_check.Parser]
config_dir = false
create_path = false

[google_charts.Parser]
line_html = false
create_layout = false
line_matplot = false
new_ref = false
error = false
show_ref = false
update_ref = false
show_package = false
single_package = "None"
library = [ "AixLib",]
funnel_comp = false
ref_txt = false

[lock_model.Parser]
library = [ "AixLib",]
lock_library = "None"

[library_merge.Parser]
library_dir = "AixLib\\Resources\\Scripts"
merge_library_dir = "modelica-ibpsa\\IBPSA\\Resources\\Scripts\\Dymola\\ConvertIBPSA_*"
mos_path = "Convertmos"
library = [ "AixLib",]
merge_library = "IBPSA"

[html_tidy_errors.Parser]
correct_overwrite = false
correct_backup = false
log = false
single_package = "None"
path = "."
whitelist = false
correct_view = false
library = [ "AixLib",]
git_url = "https://github.com/ibpsa/modelica-ibpsa.git"
filter_whitelist = false

[StyleChecking.Parser]
single_package = "None"
library = [ "AixLib",]
dymola_version = "2022"
changed_models = false

[OM_Check.Parser]
library = [ "AixLib",]
packages = [ "Airflow",]
changed_flag = true
filter_wh_flag = true
extended_ex_flag = true
load_setting_flag = false
om_options = [ "OM_CHECK",]

[reference_check.Parser]
batch = false
show_gui = false
single_package = "None"
path = "."
library = [ "AixLib",]
number_of_processors = 8
tool = "dymola"
dymola_version = "2022"
coverage_only = false
create_ref = false
ref_list = false
update_ref = false
modified_models = false
validate_html_only = false
validate_experiment_setup = false
report = false

[validatetest.Parser]
library = [ "AixLib",]
packages = [ "Airflow",]
root_wh_library = "None"
dymola_version = "2022"
changed_flag = true
filter_wh_flag = true
extended_ex_flag = true
create_wh_flag = false
load_setting_flag = false
dym_options = [ "DYM_CHECK",]
repo_dir = "None"
git_url = "https://github.com/ibpsa/modelica-ibpsa.git"

[html_tidy_errors.Parser.wh_library]
[[html_tidy_errors.Parser.wh_library.IBPSA]]
git_url = "fdgfdsg"

[[html_tidy_errors.Parser.wh_library.IBPSA]]
repo_dir = "modelica-ibpsa"

[OM_Check.Parser.root_library]
AixLib = "..\\AixLib\\AixLib\\package.mo"

[OM_Check.Parser.wh_library]
[[OM_Check.Parser.wh_library.IBPSA]]
git_url = "fdgfdsg"

[[OM_Check.Parser.wh_library.IBPSA]]
repo_dir = "modelica-ibpsa"

[validatetest.Parser.root_library]
AixLib = "..\\AixLib\\AixLib\\package.mo"

[validatetest.Parser.wh_library]
[[validatetest.Parser.wh_library.IBPSA]]
git_url = "fdgfdsg"

[[validatetest.Parser.wh_library.IBPSA]]
repo_dir = "modelica-ibpsa"

