[files]
wh_file = 'dymola-ci-tests{os.sep}ci_whitelist{os.sep}model_whitelist.txt'
ref_whitelist_file = 'dymola-ci-tests{os.sep}ci_whitelist{os.sep}reference_check_whitelist.txt'
html_wh_file = 'dymola-ci-tests{os.sep}ci_whitelist{os.sep}html_whitelist.txt'
show_ref_file = 'bin{os.sep}interact_CI{os.sep}show_ref.txt'
update_ref_file = 'bin{os.sep}interact_CI{os.sep}update_ref.txt'
chart_temp_file = 'dymola-ci-tests{os.sep}templates{os.sep}01_google_templates{os.sep}google_chart.txt'
index_temp_file = 'dymola-ci-tests{os.sep}templates{os.sep}01_google_templates{os.sep}index.txt'
layout_temp_file = 'dymola-ci-tests{os.sep}templates{os.sep}01_google_templates{os.sep}layout_index.txt'
exit_file = 'dymola-ci-tests{os.sep}Configfiles{os.sep}exit.sh'
ref_file = 'dymola-ci-tests{os.sep}Configfiles{os.sep}ci_reference_list.txt'
ch_file = 'dymola-ci-tests{os.sep}Configfiles{os.sep}ci_changed_model_list.txt'
new_ref_file = 'dymola-ci-tests{os.sep}Configfiles{os.sep}ci_new_created_reference.txt'
    

[folder]
artifacts_dir = 'dymola-ci-tests{os.sep}templates{os.sep}04_artifacts'
chart_dir = 'dymola-ci-tests{os.sep}templates{os.sep}02_charts'
ref_file_dir = 'Resources{os.sep}ReferenceResults{os.sep}Dymola'
resource_dir = 'Resources{os.sep}Scripts{os.sep}Dymola'


