[OM_Check]
install_libraries = [["Modelica_DeviceDrivers", "2.0.0", "exactMatch=true"],
                      ["SDF", "0.4.2", "exactMatch=false"]]
except_list = ["Warning: Conversion-annotation contains unknown element: nonFromVersion",
               "failed with no error message.",
               "Warning: Requested package Modelica_DeviceDrivers"]
additional_libraries_local = [["whitelist_library: os.getcwd(), modelica-ibpsa"]]

[Dymola_Check]
install_libraries = [["Modelica_DeviceDrivers", "2.0.0", "exactMatch=true"],
                      ["SDF", "0.4.2", "exactMatch=false"]]
except_list = ["Warning: Conversion-annotation contains unknown element: nonFromVersion",
               "failed with no error message.",
               "Warning: Requested package Modelica_DeviceDrivers"]
additional_libraries_local = [["whitelist_library: os.getcwd(), modelica-ibpsa"]]
