[OM_Check.Parser]
library_dict = "None"
package_dict = "None"
wh_library = "IBPSA"
changed_flag = "False"
filter_wh_flag = "False"
extended_ex_flag = "False"
load_setting_flag = "True"
om_options = "om_check"

[reference_check.Parser]
batch = "False"
show_gui = "False"
single_package = "None"
path = "."
library = "AixLib"
number_of_processors = "16"
tool = "dymola"
dymola_version = "2022"
coverage_only = "False"
create_ref = "False"
ref_list = "False"
update_ref = "False"
modified_models = "False"
validate_html_only = "False"
validate_experiment_setup = "False"
report = "False"

[validatetest.Parser]
library_dict = "None"
package_dict = "None"
wh_library = "IBPSA"
dymola_version = "2022"
changed_flag = "False"
filter_wh_flag = "False"
extended_ex_flag = "False"
create_wh_flag = "False"
simulate_flag = "False"
load_setting_flag = "False"
dym_options = "om_check"
repo_dir = "None"
git_url = "https://github.com/ibpsa/modelica-ibpsa.git"
dymola_options = "dym_check"
